ALTER TABLE users ADD COLUMN coin_balance INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN coin_day_earned INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN coin_day_key TEXT;
ALTER TABLE users ADD COLUMN coin_week_earned INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN coin_week_key TEXT;
